name: pdf_reader_app
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any  
  firebase_storage: ^11.0.7
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  audioplayers: ^3.0.1
  cupertino_icons: ^1.0.2
  syncfusion_flutter_pdfviewer: ^20.2.44-beta
  google_sign_in: ^5.4.4
  cloud_firestore: ^4.4.0
  firebase_messaging: ^14.2.2
  awesome_dialog: ^3.0.2
  http: ^0.13.5
  google_fonts: ^4.0.3
  chips_choice: ^3.0.0
  shared_preferences: ^2.1.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - images/
